In [ ]:
import os

import numpy as np
import pandas as pd

dir = "imdb_episode_images"
targetDir = os.path.abspath(dir)
targetCSV = "CSV/imdb_episodes.csv"
col = "Slug"

In [130]:
df = pd.read_csv(targetCSV)
df

,Slug,Title,Description,Rating,Rating Count,Duration,Release Date,Genres,Poster
0,tt0035599,Voice of Firestone Televues,Documentary films on diverse subjects.,NaN,NaN,NaN,1943-11-29,NaN,NaN
1,tt15340888,Lady Napoleon,"Sophie, descendant of Napoleon, leads Lady Nap...",NaN,NaN,NaN,NaN,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Lady_Napoleon.jpg
2,tt27658590,MañanaEsTooLate con Lorenzo Parro,A comedy show that serves up the funniest and ...,NaN,NaN,NaN,2020-04-07,['Comedy'],imdb_episode_images\MañanaEsTooLate_con_Lorenz...
3,tt10515284,D_Sawz Tv,NaN,NaN,NaN,NaN,2016-09-03,['Comedy'],imdb_episode_images\D_Sawz_Tv.jpg
4,tt4816058,Dragons: Race to the Edge,Unlock the secrets of the Dragon Eye and come ...,8.2,9308.0,NaN,2015-06-26,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Dragons_Race_to_the_Edge.jpg
...,...,...,...,...,...,...,...,...,...
99074,tt6403100,Everest Rescue,Rescue pilots in the Himalayas battle altitude...,8.4,81.0,NaN,2017-01-08,['Reality-TV'],imdb_episode_images\Everest_Rescue.jpg
99075,tt11994064,Antartida,5.4 million square miles. -76 degrees Fahrenhe...,7.5,12.0,NaN,2021-04-01,['Adventure'],imdb_episode_images\Antartida.jpg
99076,tt11994256,Ykkösaamu,The &quot;sister show&quot; of the radio progr...,4.4,9.0,NaN,2008-09-13,['Talk-Show'],imdb_episode_images\Ykkösaamu.jpg
99077,tt0288359,The Frost Programme,NaN,NaN,NaN,NaN,1977-06-02,['Talk-Show'],NaN
99078,tt11994996,The Fake Spaniards Show,The Fake Spaniards are a group of characters k...,NaN,NaN,NaN,2010-11-23,['Comedy'],imdb_episode_images\The_Fake_Spaniards_Show.jpg

# Actual Checking

## CSV Dupes

In [131]:
dupCount = int(df[col].duplicated().sum())

if dupCount == 0:
	print(f"No duplicates found ({dupCount})")
else:
	print(f"There are {dupCount} duplicates found")

No duplicates found (0)

In [132]:
noPosters = df["Poster"].isnull().sum()
print(f"There are {noPosters} rows with no posters")

There are 23273 rows with no posters

In [138]:
posterCount = len(df["Poster"]) - int(df["Poster"].isnull().sum())
print(f"Number of series that has poster: {posterCount}")

Number of series that has poster: 75806

In [160]:
dfCpy = df.copy()
dfCpy.dropna(subset=["Poster"], inplace=True)
dfCpy["Poster - CI"] = dfCpy["Poster"].str.upper()
dfDupPoster = dfCpy["Poster - CI"].duplicated().sum()

if dfDupPoster == 0:
	print(f"No duplicates found in Poster column ({dfDupPoster})")
else:
	print(f"There are {dfDupPoster} duplicates found in Poster column")

There are 2953 duplicates found in Poster column

In [161]:
dfCpy[dfCpy["Poster - CI"].duplicated()]

,Slug,Title,Description,Rating,Rating Count,Duration,Release Date,Genres,Poster,Poster - CI
1436,tt0044249,Chance of a Lifetime,"At first a lighthearted guessing game, the for...",NaN,NaN,NaN,1952-05-08,"['Family', 'Game-Show', 'Music']",imdb_episode_images\Chance_of_a_Lifetime.jpg,IMDB_EPISODE_IMAGES\CHANCE_OF_A_LIFETIME.JPG
1778,tt4853740,Aweful Movies with Deadly Earnest,&quot;Aweful Movies with Deadly Earnest&quot; ...,NaN,NaN,NaN,1959-10-16,"['Comedy', 'Drama', 'Fantasy']",imdb_episode_images\Aweful_Movies_with_Deadly_...,IMDB_EPISODE_IMAGES\AWEFUL_MOVIES_WITH_DEADLY_...
1787,tt4853778,Aweful Movies with Deadly Earnest,&quot;Aweful Movies with Deadly Earnest&quot; ...,6.2,11.0,NaN,1966-07-22,"['Comedy', 'Drama', 'Fantasy']",imdb_episode_images\Aweful_Movies_with_Deadly_...,IMDB_EPISODE_IMAGES\AWEFUL_MOVIES_WITH_DEADLY_...
1791,tt27722561,Wallflower,When a shy teenage girl is gifted a family hei...,NaN,NaN,NaN,NaN,['Drama'],imdb_episode_images\Wallflower.jpg,IMDB_EPISODE_IMAGES\WALLFLOWER.JPG
1823,tt4854090,Aweful Movies with Deadly Earnest,&quot;Aweful Movies with Deadly Earnest&quot; ...,NaN,NaN,NaN,NaN,"['Comedy', 'Drama', 'Fantasy']",imdb_episode_images\Aweful_Movies_with_Deadly_...,IMDB_EPISODE_IMAGES\AWEFUL_MOVIES_WITH_DEADLY_...
...,...,...,...,...,...,...,...,...,...,...
99037,tt0403726,Anna Karenina,Anna is torn between her love to Count Vronsky...,6.1,190.0,NaN,NaN,['Drama'],imdb_episode_images\Anna_Karenina.jpg,IMDB_EPISODE_IMAGES\ANNA_KARENINA.JPG
99039,tt0403728,The Big House,A spoiled rich kid has to live with his workin...,5.9,134.0,NaN,2004-04-02,['Comedy'],imdb_episode_images\The_Big_House.jpg,IMDB_EPISODE_IMAGES\THE_BIG_HOUSE.JPG
99058,tt0403759,Empire,Epic four-hour series about the rise of Octavi...,6.2,1796.0,NaN,2005-06-28,"['Action', 'Drama', 'History']",imdb_episode_images\Empire.jpg,IMDB_EPISODE_IMAGES\EMPIRE.JPG
99060,tt0403761,Face the Music,Face the Music was a light hearted classical m...,8.1,20.0,NaN,1967-08-03,['Music'],imdb_episode_images\Face_the_Music.jpg,IMDB_EPISODE_IMAGES\FACE_THE_MUSIC.JPG
99072,tt6385126,The Living Room,The Living Room is an online talk show series ...,NaN,NaN,NaN,2015-04-21,['Talk-Show'],imdb_episode_images\The_Living_Room.jpg,IMDB_EPISODE_IMAGES\THE_LIVING_ROOM.JPG

## Image Dupes

In [145]:
files = os.listdir(targetDir)
files.sort()
files = [f"{dir}\\{file}" for file in files if ".ipynb" not in file]

In [146]:
imageList = np.array(files)
imageList

array(['imdb_episode_images\\007_Gourmet_Food.jpg',
       'imdb_episode_images\\007_Road_to_a_Million.jpg',
       'imdb_episode_images\\00K9_The_Fast_and_the_Furriest.jpg', ...,
       'imdb_episode_images\\Ürgammák.jpg',
       'imdb_episode_images\\Üvey_Anne.jpg',
       'imdb_episode_images\\Üç_Kiz_Kardes.jpg'], dtype='<U157')

In [147]:
imgDf = pd.DataFrame(imageList, columns=["Images"])
imgDf

                                                  Images
0               imdb_episode_images\007_Gourmet_Food.jpg
1          imdb_episode_images\007_Road_to_a_Million.jpg
2      imdb_episode_images\00K9_The_Fast_and_the_Furr...
3                          imdb_episode_images\016FM.jpg
4                          imdb_episode_images\01_AM.jpg
...                                                  ...
72853                  imdb_episode_images\Üle_parda.jpg
72854                imdb_episode_images\Üniversdeli.jpg
72855                   imdb_episode_images\Ürgammák.jpg
72856                  imdb_episode_images\Üvey_Anne.jpg
72857              imdb_episode_images\Üç_Kiz_Kardes.jpg

[72858 rows x 1 columns]

In [156]:
imgDf["Images - CI"] = imgDf["Images"].str.upper()
imgDupCount = int(imgDf["Images - CI"].duplicated().sum())

if imgDupCount == 0:
	print(f"No duplicates found ({imgDupCount})")
else:
	print(f"There are {imgDupCount} duplicates found")

No duplicates found (0)

# Check Missing Posters

In [128]:
missingPosters = df[~df["Poster"].isin(imgDf["Images"])].copy()
missingPosters

,Slug,Title,Description,Rating,Rating Count,Duration,Release Date,Genres,Poster
0,tt0035599,Voice of Firestone Televues,Documentary films on diverse subjects.,NaN,NaN,NaN,1943-11-29,NaN,NaN
5,tt4816060,Zach and Anton Save the World,"In this sci-fi comedy, two broke friends move ...",NaN,NaN,NaN,2014-02-10,"['Comedy', 'Sci-Fi']",NaN
8,tt1051544,El kanguro de A3Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,tt0038276,You Are an Artist,Jon Gnagy was a young artist who completed dra...,NaN,NaN,NaN,1946-11-01,['Talk-Show'],NaN
15,tt0039120,Americana,Sponsored by the makers of the Encyclopedia Am...,2.9,17.0,NaN,1947-12-08,"['Family', 'Game-Show']",NaN
...,...,...,...,...,...,...,...,...,...
99065,tt11296284,Dom Does America,Dominic Littlewood travels to the United State...,7.8,15.0,NaN,2019-11-11,['Documentary'],NaN
99066,tt0224936,Novia de vacaciones,NaN,NaN,NaN,NaN,NaN,"['Drama', 'Romance']",NaN
99070,tt6325272,Steve Malzberg Show,NaN,NaN,NaN,NaN,2014-06-06,['News'],NaN
99071,tt1199397,The Vortec Power Hour,NaN,NaN,NaN,NaN,NaN,['Sport'],NaN
99077,tt0288359,The Frost Programme,NaN,NaN,NaN,NaN,1977-06-02,['Talk-Show'],NaN