In [84]:
import os

import numpy as np
import pandas as pd

dir = "imdb_episode_images"
targetDir = os.path.abspath(dir)
targetCSV = "CSV/imdb_episodes.csv"
col = "Slug"

In [85]:
df = pd.read_csv(targetCSV)
df

,Slug,Title,Rating,Date,Genres,Poster
0,tt21001980,Wild Pacific Rescue,6.8,2021-04-14,['Documentary'],imdb_episode_images\tt21001980.jpg
1,tt4816058,Dragons: Race to the Edge,8.2,2015-06-26,"['Animation', 'Action', 'Adventure']",imdb_episode_images\tt4816058.jpg
2,tt15340902,Mer panik i tomteverkstan,6.2,2021-10-02,"['Adventure', 'Comedy', 'Family']",imdb_episode_images\tt15340902.jpg
3,tt7053920,The Toys That Made Us,7.9,2017-12-22,"['Documentary', 'Comedy', 'History']",imdb_episode_images\tt7053920.jpg
4,tt1290783,Luke 11:17,8.2,2008-09-03,['Thriller'],imdb_episode_images\tt1290783.jpg
...,...,...,...,...,...,...
59876,tt18072296,Stenbeck,7.8,2013-01-03,"['Documentary', 'Biography']",imdb_episode_images\tt18072296.jpg
59877,tt35443163,Deewaniyat,9.6,2024-11-11,['Drama'],imdb_episode_images\tt35443163.jpg
59878,tt35653064,Manhunt,8.0,2025-01-14,['Documentary'],imdb_episode_images\tt35653064.jpg
59879,tt35670125,Agence Brainsto,8.8,2025-02-07,['Comedy'],imdb_episode_images\tt35670125.jpg
59880,tt7039698,Door No. 1,5.2,2018-05-24,['Comedy'],imdb_episode_images\tt7039698.jpg

# Actual Checking

## CSV Dupes

In [86]:
dupCount = int(df[col].duplicated().sum())

if dupCount == 0:
	print(f"No duplicates found ({dupCount})")
else:
	print(f"There are {dupCount} duplicates found")

No duplicates found (0)

In [87]:
df[df[col].duplicated()]

Empty DataFrame
Columns: [Slug, Title, Rating, Date, Genres, Poster]
Index: []

In [88]:
noPosters = df["Poster"].isnull().sum()
print(f"There are {noPosters} rows with no posters")

There are 0 rows with no posters

In [89]:
posterCount = len(df["Poster"]) - int(df["Poster"].isnull().sum())
print(f"Number of series that has poster: {posterCount}")

Number of series that has poster: 59881

In [90]:
dfCpy = df.copy()
dfCpy.dropna(subset=["Poster"], inplace=True)
dfCpy["Poster - CI"] = dfCpy["Poster"].str.upper()
dfDupPoster = dfCpy["Poster - CI"].duplicated().sum()

if dfDupPoster == 0:
	print(f"No duplicates found in Poster column ({dfDupPoster})")
else:
	print(f"There are {dfDupPoster} duplicates found in Poster column")

No duplicates found in Poster column (0)

In [91]:
dfCpy[dfCpy["Poster - CI"].duplicated()]

Empty DataFrame
Columns: [Slug, Title, Rating, Date, Genres, Poster, Poster - CI]
Index: []

In [92]:
dropDupes = False
"""
Determines if duplicates should be dropped. If this is set to `True`, the duplicates will be dropped and the CSV will be saved.
"""

if dropDupes:
    df.drop_duplicates(subset=["Poster"], inplace=True)
    df.to_csv(targetCSV, index=False)

## Image Dupes

In [93]:
files = os.listdir(targetDir)
files.sort()
files = [f"{dir}\\{file}" for file in files if ".ipynb" not in file]

In [94]:
imageList = np.array(files)
imageList

array(['imdb_episode_images\\tt0039123.jpg',
       'imdb_episode_images\\tt0040021.jpg',
       'imdb_episode_images\\tt0040028.jpg', ...,
       'imdb_episode_images\\tt8268134.jpg',
       'imdb_episode_images\\tt8268476.jpg',
       'imdb_episode_images\\tt8268766.jpg'], dtype='<U34')

In [95]:
imgDf = pd.DataFrame(imageList, columns=["Images"])
imgDf

                                  Images
0      imdb_episode_images\tt0039123.jpg
1      imdb_episode_images\tt0040021.jpg
2      imdb_episode_images\tt0040028.jpg
3      imdb_episode_images\tt0040033.jpg
4      imdb_episode_images\tt0040034.jpg
...                                  ...
59890  imdb_episode_images\tt8267548.jpg
59891  imdb_episode_images\tt8267738.jpg
59892  imdb_episode_images\tt8268134.jpg
59893  imdb_episode_images\tt8268476.jpg
59894  imdb_episode_images\tt8268766.jpg

[59895 rows x 1 columns]

In [96]:
imgDf["Images - CI"] = imgDf["Images"].str.upper()
imgDupCount = int(imgDf["Images - CI"].duplicated().sum())

if imgDupCount == 0:
	print(f"No duplicates found ({imgDupCount})")
else:
	print(f"There are {imgDupCount} duplicates found")

No duplicates found (0)

# Check Missing Posters

In [97]:
missingPosters = df[~df["Poster"].isin(imgDf["Images"])].copy()
missingPosters

Empty DataFrame
Columns: [Slug, Title, Rating, Date, Genres, Poster]
Index: []

In [98]:
dropMissing = False

if dropMissing:
    df.drop(missingPosters.index, inplace=True)
    df.to_csv(targetCSV, index=False)

## Missing Values

In [99]:
missingPosters[missingPosters["Poster"].isnull()]

Empty DataFrame
Columns: [Slug, Title, Rating, Date, Genres, Poster]
Index: []

# No Posters

In [100]:
missingPosters[missingPosters["Poster"].notnull()]

Empty DataFrame
Columns: [Slug, Title, Rating, Date, Genres, Poster]
Index: []